# Generated by Django 4.2.13 on 2024-06-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date'], 'verbose_name': '文章信息'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
